name: Lint CI

on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          version: 7.12.0
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: ./.node-version
          cache: npm
          cache-dependency-path: ./package-lock.json
      - name: Install dependencies
        run: npm install --force
      - name: Run lint
        run: npm run lint
