name: Test CI

on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2.2.2
        with:
          version: 7.12.0
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: ./.node-version
          cache: pnpm
          cache-dependency-path: ./pnpm-lock.yaml
      - name: Install dependencies
        run: pnpm install
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run test
        env:
          SLACK_USERNAME: ${{ secrets.SLACK_USERNAME }}
          SLACK_BOT_USER_OAUTH_TOKEN: ${{ secrets.SLACK_BOT_USER_OAUTH_TOKEN }}
          SLACK_CONTACT_CHANNEL_CONVERSATION_ID: ${{ secrets.SLACK_CONTACT_CHANNEL_CONVERSATION_ID }}
          SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
          FROM_EMAIL: ${{ secrets.FROM_EMAIL }}
          NEXT_PUBLIC_PORT: ${{ secrets.NEXT_PUBLIC_PORT }}
          NEXT_PUBLIC_LOCAL_ENV: ${{ secrets.NEXT_PUBLIC_LOCAL_ENV }}
          LOCAL_ENV: ${{ secrets.LOCAL_ENV }}
          NEXT_PUBLIC_EMAIL_ADDRESS: ${{ secrets.NEXT_PUBLIC_EMAIL_ADDRESS }}
        run: pnpm test
